// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovikjjuigooetkyubhqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92aWtqanVpZ29vZXRreXViaHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjM5ODcsImV4cCI6MjA3Mzk5OTk4N30.F83xNCFWoE6AKazGx5JQpFvWwLy-92ZxKts9Pz3V0AQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});